#base image
FROM node:12-alpine as base
WORKDIR /app
COPY src/package*.json ./

# ---- Dependencies ----
FROM base AS dependencies
RUN npm set progress=false && npm config set depth 0
RUN npm ci --only=production
RUN npm audit fix
RUN cp -R node_modules prod_node_modules

#production
FROM dependencies AS prod
COPY --from=dependencies /app/prod_node_modules ./node_modules
COPY src/ .
EXPOSE 1337
CMD [ "npm", "run", "start" ]